### ISSUE TITLE
Pls change the package name!

### ISSUE THREAD

**Issue by yueyinqiu** [byxiaobai/ToolAPI#4]
**_(merge my pull request first)_**

The current package name means that there is a company called ToolAPI.
Check out here: https://www.mcbbs.net/forum.php?mod=viewthread&tid=1079782&page=2#pid19052178

Btw, you may change the name of the project.

**Comment by byxiaobai** [comment]
太麻烦了，而且我完全没时间

**Comment by yueyinqiu** [comment]
cao
